version: "3.8"

services: 
  db:
    container_name: postgres_db
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4
    
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db
  
  
  api: 
    build: .
    container_name: "fastapi-celery"
    command: bash -c "uvicorn backend.main:app --host 0.0.0.0 --port 8080 --reload"
    ports:
      - "8080:8080"
    volumes:
      - ./backend/:/backend
    depends_on:
      - db
    restart: always
  
  redis:
    container_name: redis
    image: redis:latest

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A backend.celery_worker.celery worker --loglevel=info
    volumes:
      - .:/backend
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - api
      - redis
  
  flower:
    container_name: flower
    build: .
    command: celery -A backend.celery_worker.celery flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - api
      - redis
      - celery_worker